# Generated by Django 6.1.1 on 2026-09-27 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expatriate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('address_in_uganda', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=150)),
                ('employer', models.CharField(max_length=200)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('work_permit_number', models.CharField(max_length=100, unique=True)),
                ('work_permit_expiry', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expatriates', to='agencies.agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expatriate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
