# Generated by Django 6.1.1 on 2026-09-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expatriates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('WORK_PERMIT', 'Work Permit'), ('EMPLOYMENT_CONTRACT', 'Employment Contract'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='expatriate_documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expatriate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='expatriates.expatriate')),
            ],
        ),
    ]
